import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generatePDF = (content: string, title: string) => {
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'mm',
    format: 'a4',
  });

  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - Branding
  doc.setFillColor(6, 148, 93); // Emerald 600
  doc.rect(0, 0, pageWidth, 20, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('FundSeed Tanzania', 10, 13);
  
  // Title
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(title, 105, 35, { align: 'center' });
  
  // Divider
  doc.setLineWidth(0.3);
  doc.line(10, 40, 200, 40);

  // Content
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(content, 180);
  doc.text(lines, 15, 55);

  // Footer - Disclaimer & Page Number
  const footerY = pageHeight - 15;
  doc.setLineWidth(0.3);
  doc.line(10, footerY - 5, 200, footerY - 5);
  
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  const disclaimer = 'Disclaimer: Document generated by FundSeed AI. For informational purposes only.';
  doc.text(disclaimer, 105, footerY, { align: 'center' });
  
  const pageCount = (doc as any).internal.getNumberOfPages();
  doc.text(`Page 1 of ${pageCount}`, pageWidth - 20, footerY);
  
  doc.save(`${title.replace(/ /g, '_')}.pdf`);
};
